name: escanor
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.18.3 
  equatable: ^0.2.0
  font_awesome_flutter: ^8.4.0
  shared_preferences: ^0.4.2
  json_annotation: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img_gojek_logo.png 
    - assets/icons/icon_menu.png 
    - assets/icons/icon_saldo.png 
    - assets/icons/icon_scan.png 
    - assets/icons/icon_transfer.png 

    - assets/images/food_1.jpg
    - assets/images/food_2.jpg
    - assets/images/food_3.jpg
    - assets/images/food_4.jpg
    - assets/images/food_5.jpg
    - assets/images/promo_1.jpg
    - assets/images/promo_2.jpg
    - assets/images/promo_3.jpg
    - assets/images/promo_4.jpg

  fonts:
    - family: NeoSans
      fonts:
        - asset: assets/fonts/NeoSansStd-Regular.otf
    - family: NeoSansBold
      fonts:
        - asset: assets/fonts/NeoSansStd-Bold.otf

  
